### PR TITLE
WIP move to github actions

### PR DESCRIPTION
**Pull request by maxandersen**
not sure if worth it but here is a basic migration of the travis build to github actions

### CODE REVIEW

**Comment by maxandersen** [comment]
realized would need a gh pr build setup too. for now this is just build on develop

**Comment by emmanuelbernard** [comment]
for info I don't know how to review this. It would need to be someone else.

**Comment by gastaldi** [comment]
@maxandersen perhaps we can use https://jekyllrb.com/docs/continuous-integration/github-actions/? Not sure if you have already seen it

**Comment by gsmet** [comment]
FWIW, until we can get some GH runners dedicated to administrative tasks, I'm against this PR.

When our runner pool is exhausted on GH actions which happens quite often, we will have to wait for website changes. Meaning postponing the release announcement for instance.

**Comment by maxandersen** [comment]
superseeded by #751

**Comment by gastaldi** [comment]
Superseded by https://github.com/quarkusio/quarkusio.github.io/pull/751. Closing

**Pull request closed without merging**
