### PR TITLE
Text adjustment

### PR DESCRIPTION
**Pull request by natanielpaiva**
Text adjustment

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
@natanielpaiva you branch seems to conflict.

**Comment by natanielpaiva** [comment]
@emmanuelbernard sorry, i go verify and send pull request.

**Comment by emmanuelbernard** [comment]
It was conflicting with the develop branch as I think you worked your changes on your original branch and not on the new develop. I fixed it for you.

**Comment by natanielpaiva** [comment]
Thanks

**Pull request closed without merging**
