### PR TITLE
Fix config tables display

### PR DESCRIPTION
**Pull request by ia3andy**
## Desktop:
image

## Mobile:
`type` and `default` columns are hidden on mobile

image

### CODE REVIEW

**Comment by ia3andy** [comment]
@gsmet I used `config.css` and `config.js` from the quarkus latest master with my modification on top. I am not sure if that's the way to do it..

**Comment by ia3andy** [comment]
I also made a PR on quarkus: https://github.com/quarkusio/quarkus/pull/6273

**Comment by ia3andy** [comment]
> Friends don't let friends push a reindent commit containing non-reindent changes ;)
> 
> Otherwise this is fine, but remember that you need a similar commit on the quarkus repo where the javascript and config.css come from.

@FroMage I think the reindent was already on quarkus master: https://github.com/quarkusio/quarkus/pull/6273/files

**Comment by FroMage** [comment]
OK, sorry, you're right, since the other PR has no reformatting it's not your fault and I reviewed the changes there.

**Comment by ia3andy** [comment]
@gsmet can we merge?

**Comment by gsmet** [comment]
I would like to see the PR in the other repo finalized first. Because most of what you do here will be overwritten at the next release.

**Pull request merged**
