### PR TITLE
[DO NOT MERGE] Add missing `mvn -N io.takari:maven:wrapper`

### PR DESCRIPTION
**Pull request by ttanimichi**
This doc says "Use: ./mvnw compile quarkus:dev" but it results in the following error:

```
./mvnw
-bash: mvnw: command not found
```

### CODE REVIEW

**Comment by cescoffier** [comment]
@ttanimichi did you create the project with the `mvn` command?

**Comment by ttanimichi** [comment]
@cescoffier Yes, I have run the following command:

```
mvn io.quarkus:quarkus-maven-plugin:{quarkus-version}:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"
```

according to https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/getting-started-guide.adoc#4-bootstrapping-the-project, which doesn't generate `./mvnw` file.

**Comment by gsmet** [comment]
@ttanimichi which version of Quarkus do you use? Because the recent version should install the Maven wrapper in the project.

**Comment by ttanimichi** [comment]
@gsmet Oh, really? I'm using Quarkus v0.13.1. I'm not 100% sure, but it seems not to use Maven Wrapper.

```
2019-04-12_19:22:25_JST ~/Desktop
$ mvn io.quarkus:quarkus-maven-plugin:0.13.1:create \
>     -DprojectGroupId=org.acme \
>     -DprojectArtifactId=getting-started \
>     -DclassName="org.acme.quickstart.GreetingResource" \
>     -Dpath="/hello"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:0.13.1:create (default-cli) @ standalone-pom ---
Creating a new project in /Users/tsukuru.tanimichi/Desktop/getting-started
Configuration file created in src/main/resources/META-INF/application.properties
[ERROR] Unable to install the Maven wrapper (./mvnw) in the project
[INFO]
[INFO] ========================================================================================
[INFO] Your new application has been created in /Users/tsukuru.tanimichi/Desktop/getting-started
[INFO] Navigate into this directory and launch your application with mvn compile quarkus:dev
[INFO] Your application will be accessible on http://localhost:8080
[INFO] ========================================================================================
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.689 s
[INFO] Finished at: 2019-04-12T19:22:33+09:00
[INFO] ------------------------------------------------------------------------

2019-04-12_19:22:33_JST ~/Desktop
$ ls getting-started/
.dockerignore	pom.xml		src/

2019-04-12_19:22:59_JST ~/Desktop
$ cd getting-started/

2019-04-12_19:23:12_JST ~/Desktop/getting-started
$ ./mvnw compile quarkus:dev
-bash: ./mvnw: No such file or directory
```

`v0.13.1` is the latest version, isn't it?
https://github.com/quarkusio/quarkus/releases

```
$ mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-25T03:41:47+09:00)
Maven home: /Users/tsukuru.tanimichi/apache-maven-3.6.0
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home
Default locale: ja_JP, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.4", arch: "x86_64", family: "mac"

2019-04-12_19:33:12_JST ~/Desktop/getting-started
$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

**Comment by gsmet** [comment]
You have `[ERROR] Unable to install the Maven wrapper (./mvnw) in the project` in your log so it's somehow failing to install it.

@geoand could you check if what you did work with JDK 11 and 0.13.1?

I also wonder if we should avoid swallowing the exception as we have no clue what the issue is :/

**Comment by geoand** [comment]
@gsmet yes of course, I will check it out.

**Comment by gsmet** [comment]
@geoand I just did, it works on my laptop. @ttanimichi could you get the 0.13 branch, go to `CreateProjectMojo` line 200 and change:
```
getLog().error("Unable to install the Maven wrapper (./mvnw) in the project");
```
to 
```
getLog().error("Unable to install the Maven wrapper (./mvnw) in the project", e);
```
so we have the exception?

Then:
```
mvn clean install -DskipTests -DskipITs
```
Then in an empty directory:
```
mvn io.quarkus:quarkus-maven-plugin:0.13.2-SNAPSHOT:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"
```
and see how it goes.

**Comment by geoand** [comment]
@gsmet just tried it as well and it seems to work just fine (on Linux).

**Comment by gsmet** [comment]
Yeah, we need more info. In any case, let's not swallow the exception as it's definitely a bad idea

**Comment by geoand** [comment]
@gsmet Indeed, I will send a PR to fix it

**Comment by geoand** [comment]
@gsmet PR is at: https://github.com/quarkusio/quarkus/pull/2032

**Comment by ttanimichi** [comment]
Oh, I’ll check it in next Monday. Have a nice weekend!

2019/04/12 20:17、Georgios Andrianakis <notifications@github.com>のメール:

**Comment by gsmet** [comment]
@ttanimichi thanks! Nice week-end to you too.

**Comment by ttanimichi** [comment]
Here you are.

```
2019-04-15_15:12:15_JST ~/Desktop
$ mvn io.quarkus:quarkus-maven-plugin:0.13.2-SNAPSHOT:create \
>     -DprojectGroupId=org.acme \
>     -DprojectArtifactId=getting-started \
>     -DclassName="org.acme.quickstart.GreetingResource" \
>     -Dpath="/hello"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:0.13.2-SNAPSHOT:create (default-cli) @ standalone-pom ---
Creating a new project in /Users/tsukuru.tanimichi/Desktop/getting-started
Configuration file created in src/main/resources/META-INF/application.properties
[ERROR] Unable to install the Maven wrapper (./mvnw) in the project
org.apache.maven.plugin.MojoExecutionException: Error installing the Maven Wrapper.
    at io.takari.maven.plugins.WrapperMojo.execute (WrapperMojo.java:94)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:119)
    at io.quarkus.maven.CreateProjectMojo.createMavenWrapper (CreateProjectMojo.java:186)
    at io.quarkus.maven.CreateProjectMojo.execute (CreateProjectMojo.java:163)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: Cannot determine the type of archive /Users/tsukuru.tanimichi/.m2/repository/io/takari/maven-wrapper/0.5.3/maven-wrapper-0.5.3.tar.gz.
    at io.tesla.proviso.archive.tar.TarGzArchiveSource.<init> (TarGzArchiveSource.java:29)
    at io.tesla.proviso.archive.tar.TarGzArchiveHandler.getArchiveSource (TarGzArchiveHandler.java:44)
    at io.tesla.proviso.archive.UnArchiver.unarchive (UnArchiver.java:54)
    at io.tesla.proviso.archive.UnArchiver.unarchive (UnArchiver.java:44)
    at io.takari.maven.plugins.WrapperMojo.execute (WrapperMojo.java:83)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:119)
    at io.quarkus.maven.CreateProjectMojo.createMavenWrapper (CreateProjectMojo.java:186)
    at io.quarkus.maven.CreateProjectMojo.execute (CreateProjectMojo.java:163)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.io.IOException: Input is not in the .gz format
    at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.init (GzipCompressorInputStream.java:164)
    at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init> (GzipCompressorInputStream.java:137)
    at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init> (GzipCompressorInputStream.java:102)
    at io.tesla.proviso.archive.tar.TarGzArchiveHandler.getInputStream (TarGzArchiveHandler.java:34)
    at io.tesla.proviso.archive.tar.TarGzArchiveSource.<init> (TarGzArchiveSource.java:27)
    at io.tesla.proviso.archive.tar.TarGzArchiveHandler.getArchiveSource (TarGzArchiveHandler.java:44)
    at io.tesla.proviso.archive.UnArchiver.unarchive (UnArchiver.java:54)
    at io.tesla.proviso.archive.UnArchiver.unarchive (UnArchiver.java:44)
    at io.takari.maven.plugins.WrapperMojo.execute (WrapperMojo.java:83)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:119)
    at io.quarkus.maven.CreateProjectMojo.createMavenWrapper (CreateProjectMojo.java:186)
    at io.quarkus.maven.CreateProjectMojo.execute (CreateProjectMojo.java:163)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO]
[INFO] ========================================================================================
[INFO] Your new application has been created in /Users/tsukuru.tanimichi/Desktop/getting-started
[INFO] Navigate into this directory and launch your application with mvn compile quarkus:dev
[INFO] Your application will be accessible on http://localhost:8080
[INFO] ========================================================================================
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.748 s
[INFO] Finished at: 2019-04-15T15:12:21+09:00
[INFO] ------------------------------------------------------------------------
```

**Comment by geoand** [comment]
Thanks @ttanimichi. Can you please try deleting directory `/Users/tsukuru.tanimichi/.m2/repository/io/takari/maven-wrapper/0.5.3` and trying again please?

**Comment by ttanimichi** [comment]
Done.

```
2019-04-15_15:30:25_JST ~/Desktop
$ rm -rf /Users/tsukuru.tanimichi/.m2/repository/io/takari/maven-wrapper/0.5.3

2019-04-15_15:30:29_JST ~/Desktop
$ mvn io.quarkus:quarkus-maven-plugin:0.13.2-SNAPSHOT:create \
>     -DprojectGroupId=org.acme \
>     -DprojectArtifactId=getting-started \
>     -DclassName="org.acme.quickstart.GreetingResource" \
>     -Dpath="/hello"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:0.13.2-SNAPSHOT:create (default-cli) @ standalone-pom ---
Creating a new project in /Users/tsukuru.tanimichi/Desktop/getting-started
Configuration file created in src/main/resources/META-INF/application.properties
Downloading from central: https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.3/maven-wrapper-0.5.3.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.3/maven-wrapper-0.5.3.pom (2.4 kB at 2.3 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.3/maven-wrapper-0.5.3.jar
Downloaded from central: https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.3/maven-wrapper-0.5.3.jar (51 kB at 2.0 kB/s)
[INFO]
[INFO] Maven Wrapper version 0.5.3 has been successfully set up for your project.
[INFO] Using Apache Maven: 3.6.0
[INFO] Repo URL in properties file: https://repo.maven.apache.org/maven2
[INFO]
[INFO]
[INFO] ========================================================================================
[INFO] Your new application has been created in /Users/tsukuru.tanimichi/Desktop/getting-started
[INFO] Navigate into this directory and launch your application with mvn compile quarkus:dev
[INFO] Your application will be accessible on http://localhost:8080
[INFO] ========================================================================================
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.761 s
[INFO] Finished at: 2019-04-15T15:31:11+09:00
[INFO] ------------------------------------------------------------------------
```

**Comment by ttanimichi** [comment]
FYI. 
At first, I have run `$ mvn clean install -DskipTests -DskipITs` and the result was following:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17:26 min
[INFO] Finished at: 2019-04-15T14:18:30+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single (assemble) on project quarkus-documentation: Execution assemble of goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single failed: group id '1522739515' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :quarkus-documentation
```

To avoid this macOS’s error, I have removed the docs module from the top-level`pom.xml`.

```diff
2019-04-15_15:34:33_JST ~/Desktop/quarkus
$ git diff
diff --git a/devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java b/devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java
index c34fa06ed..d2c683dcc 100644
--- a/devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java
+++ b/devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java
@@ -197,7 +197,7 @@ public class CreateProjectMojo extends AbstractMojo {
                             pluginManager));
         } catch (Exception e) {
             // no reason to fail if the wrapper could not be created
-            getLog().error("Unable to install the Maven wrapper (./mvnw) in the project");
+            getLog().error("Unable to install the Maven wrapper (./mvnw) in the project", e);
         }
     }

diff --git a/docs/pom.xml b/docs/pom.xml
index c8848bd5f..5281266f2 100644
--- a/docs/pom.xml
+++ b/docs/pom.xml
@@ -140,6 +140,7 @@
                             <goal>single</goal>
                         </goals>
                         <configuration>
+                            <tarLongFileMode>posix</tarLongFileMode>
                             <descriptors>
                                 <descriptor>assembly.xml</descriptor>
                             </descriptors>
diff --git a/pom.xml b/pom.xml
index 819eefcd1..696006992 100644
--- a/pom.xml
+++ b/pom.xml
@@ -74,9 +74,6 @@
         <!-- Devtools (Maven, cli, gradle) -->
         <module>devtools</module>

-        <!-- Misc. -->
-        <module>docs</module>
-
         <!-- Do not add modules after war-launcher. JVM state will fail CI -->
         <module>war-launcher</module>
     </modules>
```

ref. https://maven.apache.org/plugins/maven-assembly-plugin/faq.html#tarFileModes

**Comment by geoand** [comment]
Thanks for this info @ttanimichi!

So just to confirm, you no longer have the maven wrapper problem, correct? But you are now running into a problem with the maven assembly plugin?

**Comment by gsmet** [comment]
Closing, the initial issue is fixed.

**Pull request closed without merging**
