### PR TITLE
Documentation build - Add new Docs main page and navigation.

### PR DESCRIPTION
**Pull request by insectengine**
Created new Documentation main page to replace the current guides page. This page does not have the appropriate coding to pull new guides and build properly yet. I'm creating this PR in hopes that someone on the larger team has the skillset to compete the necessary hooks to make it build properly.

I've also replaced the guides page link in the primary navigation with the new Documentation page.

### CODE REVIEW

**Comment by michalvavrik** [comment]
Just to clarify @insectengine  - currently there are categories:
_Getting Started  Core  Web  Data  Messaging  Security  Business Automation  Integration  Command Line Applications  Cloud  Observability  Serialization  Tooling  Compatibility  Miscellaneous  Alternative Languages  Writing Extensions  Architecture_

and you provided _Tutorials How-to Guides Concepts Reference Docs_

What is the intention, was the for categories above just an example, or do you suggest to leave categories above in favor of your categories? If it's later, than what has to be done is to create "hooks" so we can recognize which "guide" (current meaning) is _Tutorial, Concept, Reference_ ..., right?

**Comment by insectengine** [comment]
@michalvavrik - Are you working with Erin Schnabel @ebullient on this? The html build I created was for the final form of this page when we've transitioned the documentation to the diataxis framework. It's a work in progress so I'm working with Erin to display an intermediate step.

**Comment by michalvavrik** [comment]
@insectengine I see, never mind, I misunderstood description and wanted to help. No, I don't belong to Quarkus team. Thanks for quick reply

**Comment by insectengine** [comment]
Iterative step/blended approach until we have all the docs in the new diataxis framework.

[****](https://xd.adobe.com/view/86c47f8c-3c62-4227-9e07-9b5d16e0d928-d397/)

**Pull request closed without merging**
