### PR TITLE
Add working groups page and layout

### PR DESCRIPTION
**Pull request by cescoffier**
- Provide the script that generate the wg.yaml
- Create a workflow that update the working group yaml periodically
- Add the wg page and layout
- A bit of CSS to make the page looks ok

### CODE REVIEW

**Comment by cescoffier** [comment]
@gsmet Can you have a look when you are back?

**Review by gsmet — APPROVED** [review]
A few comments but nothing blocking:

- we need a dark theme for the cards (and probably more love from @insectengine)
- you're talking about contacting a point of contact but there's none
- not completely sure about having `wg` as the url. I would have gone with `working-groups` for better SEO. You will have a link or a bookmark.
- we need to include it in the nav somewhere (probably something to discuss with @insectengine )

In any case, nothing blocking, I let you address what you think makes sense and merge.

**Comment by insectengine** [comment]
@gsmet - I'll look at the styling and light/darkmode

**Comment by insectengine** [comment]
workinggroups_styling_dark
workinggroups_styling_light
workinggroups_nav

1) Took some liberties with the intro text.
2) Used styling from our existing card styling and removed the grey backgrounds on the header/footer of the cards.
3) Changed from 2 columns to 3.
4) Replaced the outbound board buttons with links as "buttons do things, links go places" (even though we're not 100% compliant elsewhere). The buttons also broke the mobile view.
5) Revised the date format in yaml to sync with other pages (newsletter, insights, etc)
6) Made light/dark mode compliant.
7) Added to "Community" section of site as this is shows users how to contribute/participate.

**Comment by insectengine** [comment]
Now, I need to figure out how to get my changes into Clement's PR.

**Comment by gsmet** [comment]
I will close this one so that we iterate on yours.

**Pull request closed without merging**
