### PR TITLE
Change reactive feature on the landing page

### PR DESCRIPTION
**Pull request by cescoffier**
Update the "reactive" core feature on the landing page to be more in phase with the current (and next to be) continuum page content.

### CODE REVIEW

**Comment by holly-cummins** [comment]
I'm not sure "Continuum" on its own tells a reader very much about what they might find if they click on it. People wouldn't tell their boss "Yeah, we have to switch to Quarkus because it has *continuum*."

I do like the [homepage-features-icon-band.html](https://github.com/quarkusio/quarkusio.github.io/pull/2114/files#diff-4da0a5de4f1dde18369f8d653effba4ea8e1389ad9e7b0bd9b1ce1ecf9f74b2d) changes, though.

**Comment by holly-cummins** [comment]
> I agree "continuum" is not great. But it's way better than "reactive" which point to a page barely mentioning reactive.

You're right, this is hard. I never thought to look at the link, and now that I've done it, I'm not entirely sure what the page is about. So I agree, "Reactive" is not right and should be changed. 

> What about versatility?

+1. I think that does a better job of capturing the user-facing value. (And also of summarising what that page is trying to say.)

**Comment by cescoffier** [comment]
@holly-cummins - wording changed in the menu.

**Review by holly-cummins — APPROVED** [review]

**Comment by holly-cummins** [comment]
Will mirror to http://quarkus.io/extensions once this merges.

**Pull request merged**
