### PR TITLE
Stargate user story

### PR DESCRIPTION
**Pull request by edeandrea**
User story blog post: Stargate selects Quarkus for its V2 implementation

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by edeandrea** [comment]
I have 1 small edit I need to make this morning before this gets merged.

**Comment by edeandrea** [comment]
@gastaldi I've made the small edit. This is good to go. If possible, I'd like this to go live on Monday 12/19 (that's what I have set in the metadata).

**Comment by gsmet** [comment]
(just a quick note that if merged before, it will be automatically published on Monday)

**Comment by edeandrea** [comment]
> (just a quick note that if merged before, it will be automatically published on Monday)

Yep I know - was just mentioning that to see if this could get merged before/during the weekend so that it would be ready on Monday :)

**Comment by gastaldi** [comment]
Can you also add it to https://github.com/quarkusio/quarkus/blob/main/ADOPTERS.md?

**Comment by edeandrea** [comment]
> https://quarkus-io-pr-1591-preview.surge.sh

Done: https://github.com/quarkusio/quarkus/pull/29892

**Comment by gastaldi** [comment]
> (just a quick note that if merged before, it will be automatically published on Monday)

Awesome, let's merge this then

**Comment by edeandrea** [comment]
Thanks @gastaldi & @gsmet !

**Pull request merged**
