### PR TITLE
Remove blue title background

### PR DESCRIPTION
**Pull request by insectengine**
Rethinking the use of the large blue background element at the top of each page to contain the Page Title and subtitle. This change would improve readability on all resolutions (desktop, tablet and mobile).

### CODE REVIEW

**Comment by gsmet** [comment]
No strong opinion on my side on that one :).

To see the difference:
- https://quarkus-io-pr-1650-preview.surge.sh/container-first/
- vs https://quarkus.io/container-first/

Note that we have a big warning for surge.sh now (at least on my browser, I got to the site by clicking Ignore)

/cc @gastaldi @maxandersen

**Comment by gastaldi** [comment]
No strong opinion here either, but to be honest I like the blue background :)

**Comment by maxandersen** [comment]
I must be missing something. On my phone the blue seems easier to read as more contrast?

**Comment by insectengine** [comment]
We've already removed it a while ago on the guides page to clean up the experience of that page (makes the blue filter bar more prominent). 

https://quarkus.io/guides/

If y'all like the rest of the site with the blue bar, we can kill this PR. Just making a suggestion. No worries.

**Pull request closed without merging**
