### PR TITLE
Add post about JFR in native mode

### PR DESCRIPTION
**Pull request by roberttoyonaga**
Added a post about JFR in native mode. This basically a re-post that includes a brief introduction then links to two recent Red Hat Developer articles.

### CODE REVIEW

**Review by galderz — APPROVED** [review]

**Comment by galderz** [comment]
Checked the preview and looks good. You'll probably need to adjust the blog post date cc @gsmet. Anything else to add @maxandersen?

**Comment by galderz** [comment]
@roberttoyonaga Can you add `native` as tag?

**Comment by galderz** [comment]
Also, it now has a conflict that needs to be resolved.

**Comment by galderz** [comment]
Also @roberttoyonaga, can you update the date?

**Comment by roberttoyonaga** [comment]
Yup! Date updated, conflict resolved, and native tag added

**Comment by gsmet** [comment]
I made a few minor adjustments (mostly adding some line returns/bullet list and use `native executables` instead of `native mode` as that's what we prefer).

I schedule the publication for Monday as Friday is a very slow day.

If you want me to tweet it from the Quarkusio Twitter account, feel free to write a tweet here and I'll publish it.

**Comment by galderz** [comment]
Thanks @gsmet for the quick turnaround!

**Pull request merged**
