### PR TITLE
Update wg template output

### PR DESCRIPTION
**Pull request by marko-bekhta**
Localized sites are failing the sync, e.g. https://github.com/quarkusio/ja.quarkus.io/actions/runs/11649704974/job/32437525219

This was originally fixed here https://github.com/quarkusio/quarkusio.github.io/pull/2098

But looks like the wg sync action was executed (https://github.com/quarkusio/quarkusio.github.io/commit/cedef7aad351af43b8e202fa3ca20b1801a39c67) that added back the file without the `.template`

### CODE REVIEW

**Comment by cescoffier** [comment]
This is breaking the sync.
Why this was merged without review?

**Comment by cescoffier** [comment]
I honestly don't know how this is fixing the issue and for sure it's not working anymore, as the new data is in a new file.

**Comment by marko-bekhta** [comment]
the sync of localized sites...

**Comment by cescoffier** [comment]
What does it need? The WG sync is very simple, it just runs a script updating a file under _data.

**Comment by cescoffier** [comment]
I don't know what that line is doing:
```
subprocess.CalledProcessError: Command 'PERLLIB=vendor/po4a/lib vendor/po4a/po4a-updatepo --msgmerge-opt --no-fuzzy-matching --master-charset UTF-8 -f yaml --master upstream/working-groups/templates/wg.yaml --po l10n/po/ja_JP/working-groups/templates/wg.yaml.po' returned non-zero exit status 255.
```

But I guess it's where the issue needs to be fixed -  not by breaking the working group sync process.

**Comment by marko-bekhta** [comment]
ooook ... let me try to summarize it.

see the sync of a localized site e.g. this one: https://github.com/quarkusio/ja.quarkus.io/actions/runs/11649704974/job/32437525219

the problem is in the `templates/wg.yaml`. Which was already renamed in the past (in this PR https://github.com/quarkusio/quarkusio.github.io/pull/2098) to a `wg.yml.template`. 

with the changes merged in this PR https://github.com/quarkusio/quarkusio.github.io/pull/2041/files
the `templates/wg.yaml` was added back for some reason (while it should've not).

**Comment by marko-bekhta** [comment]
now see this PR: https://github.com/quarkusio/quarkusio.github.io/pull/2155
which I opened right away after realizing that the update to the GH action was wrong ...

**Comment by yrodiere** [comment]
> Why this was merged without review?

It was merged with my review, I just did not formally add the approval. And, apparently, was wrong. Sorry.

Do I understand correctly that #2155 fixed things?

**Comment by cescoffier** [comment]
I approved and merged #2155 - thanks!

@yrodiere it reverses the WG sync change that broke it. But it does not fix the localized web site issue.

**Comment by cescoffier** [comment]
@yrodiere @marko-bekhta 

Seems like the issue in in https://github.com/doc-l10n-kit/quarkus-l10n-utils/blob/main/lib/quarkus_l10n_utils/po_manager.py#L146. But it's calling a perl script.

**Comment by cescoffier** [comment]
I fear it's this: https://github.com/mquinson/po4a/blob/326600634c81a49b41fe5e4e1bfaae2847e0963d/po4a-updatepo#L16 (My Perl is a bit rusty)

**Pull request merged**
