### PR TITLE
Fixed typo from DockerFile.native -> Dockerfile

### PR DESCRIPTION
**Pull request by danieloh30**

### CODE REVIEW

**Comment by cescoffier** [comment]
@danieloh30 the content sounds right, which version of quarkus are you using?

**Comment by danieloh30** [comment]
@cescoffier Where can I find out the version? I cloned the Quarkus.io repo 2 days ago.

**Comment by cescoffier** [comment]
@danieloh30 If you use `master` it should be `999-SNAPSHOT` in the `pom.xml` file.

**Comment by danieloh30** [comment]
@cescoffier In my case, <version>1.0-SNAPSHOT</version>

Should I pull the repo again?

**Comment by cescoffier** [comment]
Oh, 0.11.0 is quite outdated :-) We are already on the 0.13.1. (yes, we move fast)

**Comment by danieloh30** [comment]
Let me try after cloning 0.13.1. Btw, DockerFile.native in the doc is wrong, isn't it?

**Comment by gsmet** [comment]
@danieloh30 it shouldn't be: you should have 2 different Docker files now.

**Comment by danieloh30** [comment]
@gsmet How come? The latest repo[1] still has one Dockerfile.

[1]https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started/src/main/docker

**Comment by gsmet** [comment]
@geoand I have a vague recollection that you created two different `Dockerfile` for native and jvm. Am I misremembering it? Or maybe we haven't updated the quickstart?

**Comment by geoand** [comment]
@gsmet That is correct, I was the one that introduced the second Dockerfile and renamed the existing one. It seems like I indeed forgot to update the quickstarts. Would you like me to do that? If so, should the PR be against `master` or `development`?

**Comment by gsmet** [comment]
@geoand all PRs on quickstart should now be for the `development` branch. You will see it in the PR template :).

**Comment by geoand** [comment]
> @geoand all PRs on quickstart should now be for the `development` branch. You will see it in the PR template :).

Gotcha :wink:

**Comment by geoand** [comment]
PR in quickstarts ready: https://github.com/quarkusio/quarkus-quickstarts/pull/152

**Comment by gsmet** [comment]
@danieloh30 good catch. @geoand fixed the quickstarts, it should be OK in the next release. Thanks for raising the issue.

**Pull request closed without merging**
