### PR TITLE
@Stream was renamed to @Channel

### PR DESCRIPTION
**Pull request by kenfinnigan**

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks!

Let's wait before merging this as Adela is working on some changes in this area. I'll rebase and merge as soon as she's done.

**Comment by kenfinnigan** [comment]
No problem, I just happened to see it and felt it should be fixed

**Comment by gsmet** [comment]
The file was dropped and renamed so I pushed the change to the new file.

Should be pushed to the website soon.

**Comment by gsmet** [comment]
Thanks!

**Pull request closed without merging**
