### PR TITLE
Add some keywords for the CDI-related guides

### PR DESCRIPTION
**Pull request by gsmet**
/cc @mkouba @gastaldi @geoand I added this feature recently. I added some keywords for the SSO-related guides and in this PR I add some for CDI (I was looking for things in the CDI doc).

If you think of others, be my guest. They are not visible but are included in the search engine.

Obviously, we don't want too many either as we don't want all the guides to pop up when looking for something but some others might be useful.

It's not pressing but I thought it could be useful to make you aware of it.

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for the heads up!

Really useful indeed!

**Review by mkouba — APPROVED** [review]
LGTM.

OT: I'd like to show the `cdi` and `cdi-reference` guides when `arc` is used in the search box. What should I do? Do I need to modify the description, or?

**Comment by gastaldi** [comment]
> OT: I'd like to show the `cdi` and `cdi-reference` guides when `arc` is used in the search box. What should I do? Do I need to modify the description, or?

I think you just need to add the `keywords: arc` to these guides

**Comment by gsmet** [comment]
Exactly, that's the whole point of this. We can add keywords without having to make the description hard to read.

Thanks @gastaldi for adding `arc`, let's merge this!

**Pull request merged**
