### PR TITLE
Color Mode Switcher and nit fixes

### LINKED ISSUE #1809: Enhance Quarkus Docs page with Dark mode
### Description

As stated in the title, to enable a Dark mode option for the docs page. Nothing fancy nor complicated, but focusing on readability.

OS sync for initial configuration would be a nice to have thing, but not necessary.

Current docs:
https://quarkus.io/guides/cache
image

### Implementation ideas

Maybe something similar to GitHub's Dark dimmed: grey (non black background and non white text).

GitHub:
image

I know colors are a preference and relative, but if some people like a darker (or lighter) mode, maybe it can be expanded to:

- Lighter (whiter or current)
- Light (current or darker current)
- Dark (grey)
- Darker (black)

### PR DESCRIPTION
**Pull request by insectengine**
resolves #1809

Builds upon @holly-cummins 's work in [PR 1954](https://github.com/quarkusio/quarkusio.github.io/pull/1954)

1) Added color mode switcher in navigation (that changes to show state: light, dark, system).
2) Fixed pre code color issue in darkmode
3) Added solution for images in blog/guides with transparency in dark mode.

Outstanding issue: Still need Guides index fix for icons in dark mode

### CODE REVIEW

**Comment by insectengine** [comment]
Removing PR to fix a significant error.

**Review by gsmet — CHANGES_REQUESTED** [review]
I had a quick look: seems to work fine.

I have one small gripe though: the avatar pictures shouldn't have a padding or it makes them really weird.

See https://quarkus-site-pr-1962-preview.surge.sh/blog/search-indexing-rollover/ for instance.

**Comment by insectengine** [comment]
@gsmet  - Fixed the gravatar images

**Comment by insectengine** [comment]
@gsmet - I'm not sure what I need to do next to move this forward. I've committed the changes you requested.

**Review by insectengine — COMMENTED** [review]
These changes addresses your comment

**Review by gsmet — APPROVED** [review]
LGTM.

Let's merge it and gather feedback from the field.

Thanks for your patience!

**Comment by gsmet** [comment]
@insectengine sorry I was on PTO and juggling with priorities!

**Pull request merged**
