### PR TITLE
Added blog logic

### PR DESCRIPTION
**Pull request by adelasofia**
Added the blog functionality to the site. Please review and make sure it works as expected before merging (I have added a dummy post in /_posts)

A few things to note:

- All blog posts in AsciiDoc format will go into the /_posts directory. 
- Images for the posts will go inside /assets/images/posts and the following line will need to be included in the AsciiDoc file `:imagesdir: /assets/images/posts`
- The URL format for the blog posts is the following: `/blog/:title/` --this can be easily changed in [_config.yml](https://github.com/adelasofia/quarkusio.github.io/blob/0e7d9c0d56d85c5fbd3e528dea39b33dd5e4119b/_config.yml#L69) or just let me know and I'd be happy to update it.
- I've added the link to the blog index page to the nav, but it is commented out at the moment. When you're ready to launch the blog just uncomment [these lines ](https://github.com/adelasofia/quarkusio.github.io/blob/0e7d9c0d56d85c5fbd3e528dea39b33dd5e4119b/_includes/header-navigation.html#L23-L25)
- Authors can be added/edited in [/_data/authors.yml](https://github.com/quarkusio/quarkusio.github.io/blob/b71bf96891ffe22d39a6bd7d2c2b11d14324d5ec/_data/authors.yaml) and they need to be added to the blog posts' front matter like [this example](https://github.com/quarkusio/quarkusio.github.io/pull/154/files#diff-e80d62f7521302fc49ec20b0a5115571R4)
- The blog index page '/blog/' will display all of the existing blog posts, and will paginate after 4 posts. You ca change the # of posts it paginates on [here](https://github.com/quarkusio/quarkusio.github.io/blob/b71bf96891ffe22d39a6bd7d2c2b11d14324d5ec/_config.yml#L86)

I'll be updating CONTRIBUTING.md in the next few days with more specific instructions.

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Thanks @adelasofia, tried it out and works great.

The one thing I'm not sure on is whether the blog list and blog pages should have the completely black background, or the same one as the guides?

Thoughts @cescoffier, @n1hility, @emmanuelbernard?

**Comment by jkbrock** [comment]
@kenfinnigan, originally /getting-started was the only page that was supposed to have the header background image. However, it has evolved into a form that doesn't cause any major UX problems. And since consistency is more important than anything, we need to decide if we want to keep or remove that header on /blog, /blog/post, /extensions, /community, and /guides. 

Whichever is chosen, image or no-image, should apply to all.

**Comment by kenfinnigan** [comment]
I think it was probably me that made that change during release craziness!

Ok, then it's probably for @n1hility and @emmanuelbernard to decide what we should do for the background on all

**Comment by emmanuelbernard** [comment]
I like the header background now that we made it not overlap titles. It gives identity to the site.

**Comment by kenfinnigan** [comment]
@emmanuelbernard so you're +1 to the background that's used on the Guides?

**Comment by emmanuelbernard** [comment]
Yes

**Comment by kenfinnigan** [comment]
@adelasofia, could you update the PR to use the different background? Thanks

**Comment by adelasofia** [comment]
@kenfinnigan done 👍

**Comment by kenfinnigan** [comment]
Thanks @adelasofia

**Pull request merged**
