### PR TITLE
Updates Blog pages

### PR DESCRIPTION
**Pull request by adelasofia**
Updates the /blog, blog post layout, and the blog tag archives layout to follow directions on [DESIGN-1915](https://issues.redhat.com/browse/DESIGN-1915)

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
Hey @adelasofia 
I found a few bugs (might have been there earlier).
If you render 
http://localhost:4000/blog/tag/GraphQL/ vs http://localhost:4000/blog/
you will see that the tags are not ordered similarly (GraphQL is at the top in one and close tot he bottom in another.
Also I think we should `lowercase` tags.

**Comment by adelasofia** [comment]
@emmanuelbernard I've updated 'Tags:' to be lowercase, but I'm not sure what you're referring to regarding the tags not being ordered similarly. Would you mind posting a screenshot of what you mean?

**Comment by emmanuelbernard** [comment]
there you go, check for the tag GraphQL in these two pages. They do now show up in the same spot.

Screenshot 2020-07-15 at 13 45 46
Screenshot 2020-07-15 at 13 46 10

**Comment by emmanuelbernard** [comment]
@adelasofia ^

**Comment by adelasofia** [comment]
@emmanuelbernard are you sure you're looking at the correct build? The screenshots you shared do not have any of the new styles applied and I haven't been able to recreate the bug.

**Comment by emmanuelbernard** [comment]
Oh I looked at quarkus.io the live website.

**Comment by gsmet** [comment]
Hi @adelasofia ,

I had a quick look and here are a few comments:
- the lines between the blog posts is not centered anymore, it's significantly more to the left
- I'm pretty sure the `GraphQL` tag is first because it's uppercase, I will change it to lowercase as it should have been that way.

Could you have a look at the first issue? It's not fundamental but if it's a quick fix for you, that would be nice.

**Comment by gsmet** [comment]
Also I'm wondering if calling the page `Quarkus Blog` instead of `Blog` could help with SEO?

**Comment by adelasofia** [comment]
@gsmet I've pushed both fixes 👍

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
