### PR TITLE
Search through https://search.quarkus.io

### PR DESCRIPTION
**Pull request by yrodiere**
Creating as draft, for discussion. Please do not merge yet.

Summary of the changes:

* Search in `/guides` and `/version/*/guides` is now implemented with a Vue.js application, replacing the custom Javascript of `search-filter.js`.
* Search is performed remotely by https://github.com/quarkusio/search.quarkus.io
* When https://github.com/quarkusio/search.quarkus.io fails to respond in a reasonable time (currently 400ms) or errors out, we default to Javascript search (basically the same implementation than before, just without JQuery)
* When searching, we no longer display anything else than matching cards (no category headings in particular). This allows ordering hits by score (relevance to the searched terms).

To test locally:

* Start https://github.com/quarkusio/search.quarkus.io locally (`quarkus dev`)
* Run the website (`./serve.sh` or `docker compose up`)
* Do a search at http://localhost/guides

You should notice search results are slightly more relevant, though we didn't try to tune search very much for now. You will see improvements though, e.g. matches against content that is not in the title/summary but elsewhere in the guide

### CODE REVIEW

**Comment by ynojima** [comment]
If this supports localized sites (es.quarkus.io, pt.quarkus.io, cn.quarkus.io, and ja.quarkus.io), it's really appriciated :)

**Comment by ynojima** [comment]
Not sure about other locales, but speaking of ja.quarkus.io, which I'm working on, all the v2.7 guides are localized (https://ja.quarkus.io/version/2.7/guides/), and more than half of the latest v3.5 guides are localized(https://ja.quarkus.io/guides/).

**Comment by yrodiere** [comment]
> Not sure about other locales, but speaking of ja.quarkus.io, which I'm working on, all the v2.7 guides are localized (https://ja.quarkus.io/version/2.7/guides/), and more than half of the latest v3.5 guides are localized(https://ja.quarkus.io/guides/).

That's definitely different from the other guides, but sure we can index that as well.

Could you please open an issue at https://github.com/quarkusio/search.quarkus.io with some information on where to find these guides (GitHub repo, path in the repo in particular).

Also I have zero experience with search in Japanese and can't even read it, so it's definitely going to be challenging to tune it for good relevance; I'll need feedback from someone who can understand the results.

**Comment by ynojima** [comment]
> I'll need feedback from someone who can understand the results.

Of course I'm happy to help this :)

I filed an issue: https://github.com/quarkusio/search.quarkus.io/issues/33
If the issue is not easy and you need to focus on the original quarkus.io search for initial release, adding a flag to jekyll configuration file to hide the search box helps localized sites.

**Comment by maxandersen** [comment]
I tried a few queries but didn't spot much difference in list of matches - wondering if i'm just choosing bad ones that are already tagged :) Got some good examples?

One thing I did notice is that search no longer retain tutorials/concepts/references section titles - is that intentional? The order still seem to be the exact same as old one thus not sure ?

**Comment by yrodiere** [comment]
Hey @edewit @ia3andy , I've been told you know your way around Javascript :)
I don't, but I did what I could with the vue.js application in this PR.

When you find some time, would you be so kind as to review this? It's probably never going to be perfect, but I'd like to at least avoid obvious mistakes...

I added instructions on how to run it locally in the PR description, and you can test it live here: https://quarkus-website-pr-1825-preview.surge.sh/guides/

@brunobat reported one bug already: it seems that if you type relatively fast in the text box, characters get mangled.

I think it comes from the fact the text box gets refreshed while you type. I don't know why it even gets refreshed since, well, it's supposed to be write-only, but maybe you have an idea?

**Comment by brunobat** [comment]
I recorded a video to demo the effect:
https://github.com/quarkusio/quarkusio.github.io/assets/2318030/e71167a9-653a-4ab7-98e7-83c2ef166b24

**Comment by gsmet** [comment]
I played a bit more with it today and given the search is using a AND when fallabacking to Javascript, I would lean towards also using a AND when using the service.

**Comment by yrodiere** [comment]
> I played a bit more with it today and given the search is using a AND when fallabacking to Javascript, I would lean towards also using a AND when using the service.

https://github.com/quarkusio/search.quarkus.io/pull/43

**Comment by yrodiere** [comment]
FWIW the search service now indexes the full HTML body of each guide, which includes e.g. configuration property references. So the search now matches on configuration properties.

cc @michelle-purcell

**Comment by ia3andy** [comment]
My only concern is that we already use Lit and React in other Quarkus project (code.quarkus and DevUI) using yet another framework will make think hard to maintain in the future. Would it be possible to switch to LitElement?

**Comment by yrodiere** [comment]
> My only concern is that we already use Lit and React in other Quarkus projects (code.quarkus and DevUI) using yet another framework will make things hard to maintain in the future. Would it be possible to switch to LitElement?

If someone sends a PR, sure. Personally I've already spent a few days just making it work, so I can't afford to spend a week learning another framework **and** trying to make it work...

**Comment by ia3andy** [comment]
> > My only concern is that we already use Lit and React in other Quarkus projects (code.quarkus and DevUI) using yet another framework will make things hard to maintain in the future. Would it be possible to switch to LitElement?
> 
> If someone sends a PR, sure. Personally I've already spent a few days just making it work, so I can't afford to spend a week learning another framework **and** trying to make it work...

From what I've looked, there is not much UI code yet, so better choose wisely. Also if you look at Lit, it seems really close to the code you provided (I am not familiar with Vue either) so I don't think it will be a big gap from one to the other...

**Comment by yrodiere** [comment]
> From what I've looked, there is not much UI code yet

That's related to my concern. When I say I'm not good at Javascript, I mean it. This "not much" literally took me days of back and forth to get something that *seems* to work (with that one remaining bug...).

In fact I'm pretty sure I've spent as much time on the frontend than on the backend at this point... If we exclude OpenShift deployment :D

> Also if you look at Lit, it seems really close to the code you provided (I am not familiar with Vue either) so I don't think it will be a big gap from one to the other...

And there you have it: "not much UI code" => a few days; "not a big gap" => how many more days?

I really can't afford to spend that kind of time right now, especially since this is essentially a side project and I'm late on pretty much every main project I'm assigned to (Hibernate Search, Quarkus Hibernate extensions, ...).

I if you feel strongly about this I'd gladly accept a patch from an expert like you that basically erases my stuff with the same features (including infinite scrolling etc.) but on a better framework and with better code.

**Comment by yrodiere** [comment]
> @brunobat reported one bug already: it seems that if you type relatively fast in the text box, characters get mangled.
> 
> I think it comes from the fact the text box gets refreshed while you type. I don't know why it even gets refreshed since, well, it's supposed to be write-only, but maybe you have an idea?

I had an idea this weekend and it turns out that was the right one: debouncing in setters causes this bug, we must debounce in watchers/methods instead. I force-pushed an updated version.

@brunobat Could you please check you no longer have the problem once the new version is deployed?
No idea how fast surge.sh deployment is, but I guess it should be there in an hour, worst case.

**Comment by yrodiere** [comment]
> I tried to search for a configuration property called `quarkus.native.reuse-existing` that's in the Native executable guide and got zero results:

@michelle-purcell 

Hmm that worked for me... 

image

Did you test that recently?

If you're on a very high-latency connection, or if you tested this while the backend was deploying, it's possible search falled back to client-side javascript search... You can check that by opening the browser console (F12 in your browser, 'Console' tab): if a problen occurred, there should be a message saying something like "Could not run search".

**Comment by yrodiere** [comment]
> > I tried to search for a configuration property called `quarkus.native.reuse-existing` that's in the Native executable guide and got zero results:
> 
> @michelle-purcell
> 
> Hmm that worked for me...

Oh, I just managed to reproduce it! Seems like on the very first search on a freshly opened browser, the call to the backend times out... I suspect some cached operation (SSL certificate retrieval?) is way too slow on our current staging environment.

Also, I just plain can't reach https://quarkus-website-pr-1825-preview.surge.sh/guides/ when I'm on company VPN, so... there's that -_-

Until I manage to find a way to fix that, can you just test with VPN off and ignore the result of your very first search?

**Comment by brunobat** [comment]
@yrodiere Just checked https://quarkus-website-pr-1825-preview.surge.sh/guides/ and the search box now works well for me.
Thanks!

**Comment by michelle-purcell** [comment]
@yrodiere - When I log out of the VPN it works for me too! Thank you :tada: 

image

**Comment by ia3andy** [comment]
I am currently working on a rewrite of the vue js app in Lit, please let me know if you make any change to the vue script.

**Comment by marko-bekhta** [comment]
Hey @ia3andy there's a pending PR (https://github.com/yrodiere/quarkusio.github.io/pull/1) with some changes to the vue script 🙈

**Comment by ia3andy** [comment]
> Hey @ia3andy there's a pending PR ([yrodiere#1](https://github.com/yrodiere/quarkusio.github.io/pull/1)) with some changes to the vue script 🙈

thanks @marko-bekhta for mentioning, I will try to also integrate this. Note that I will start with the base and we might need to re-add those features.

**Comment by yrodiere** [comment]
FYI we've merged backward-incompatible changes to the search.quarkus.io API, so the preview will fall back to javascript search until it gets updated (I already pushed the changes, we just need to wait for things to get pushed to surge.sh).

**Comment by yrodiere** [comment]
I pushed an update this morning to use the new domain (`search.quarkus.io`), but it seems the preview wasn't updated.... ?

I'll try pushing again.

**Comment by yrodiere** [comment]
We have just agreed to merge this early next year: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/search.2Equarkus.2Eio/near/409365021

**Comment by maxandersen** [comment]
tried finding info about "quarkus.websocket.max-frame-size" but couldn't get it to show something relevant.

tried the full string with and without quotes - also tried "max-frame-size" and even with quotes it kept searching for individual parts.

Should have found at least https://quarkus.io/guides/all-config that has it mentioned.

**Comment by yrodiere** [comment]
> tried finding info about "quarkus.websocket.max-frame-size" but couldn't get it to show something relevant.
> 
> tried the full string with and without quotes - also tried "max-frame-size" and even with quotes it kept searching for individual parts.
> 
> Should have found at least https://quarkus.io/guides/all-config that has it mentioned.

FWIW this is being discussed there: https://github.com/quarkusio/search.quarkus.io/pull/117

**Comment by yrodiere** [comment]
> > tried finding info about "quarkus.websocket.max-frame-size" but couldn't get it to show something relevant.
> > tried the full string with and without quotes - also tried "max-frame-size" and even with quotes it kept searching for individual parts.
> > Should have found at least https://quarkus.io/guides/all-config that has it mentioned.
> 
> FWIW this is being discussed there: [quarkusio/search.quarkus.io#117](https://github.com/quarkusio/search.quarkus.io/pull/117)

Fixed and deployed just now. Try it out :)

**Comment by yrodiere** [comment]
Merged! Thanks all for your comments.

If you notice any problems, please report to https://github.com/quarkusio/search.quarkus.io/issues

**Pull request merged**
