### PR TITLE
Attempt to reduce the number of style recalc

### PR DESCRIPTION
**Pull request by mkouba**
- related to #941

This could help a little. Unfortunately, I can't test the whole site locally (no functional ruby env here).

### CODE REVIEW

**Comment by mkouba** [comment]
We could also try to skip this part completely: https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/javascript/config.js#L257-L260

**Comment by FroMage** [comment]
Actually, I believe we need to work on the shadow table for this to work. Lemme give it a try. But damn I had garbage collected the memory of this :(

**Comment by FroMage** [comment]
I've done this with a shadow DOM, at the cost of some false positives, but the time required for setting it up is now down to 250ms on my machine. We should have done this long ago, but initially there was no need since we had much fewer entries.

The problem is that our script doesn't get called until quite a long time, because _something_ is taking forever and delays the page load. I'm not sure what, though.

**Comment by FroMage** [comment]
Note that this actually needs fixing in the quarkus repo, not just here.

**Comment by FroMage** [comment]
@mkouba @gsmet we should merge this somehow, no?

**Comment by mkouba** [comment]
> @mkouba @gsmet we should merge this somehow, no?

+1 I've tried the the [preview page](https://quarkusio-quarkusio-github-io-preview-pr-942.surge.sh/guides/all-config) and it seems to load faster...

**Comment by gsmet** [comment]
@FroMage I can merge it for sure. I'll let you fix it in the Quarkus repo as you said it was needed?

**Comment by FroMage** [comment]
> @FroMage I can merge it for sure. I'll let you fix it in the Quarkus repo as you said it was needed?

well, yeah, that's the source, when you make a release, no?

**Comment by gsmet** [comment]
Yes if this file is coming from the main repo, it needs an update before the next release (probably next Wednesday).

**Comment by FroMage** [comment]
Done: https://github.com/quarkusio/quarkus/pull/16436

**Pull request merged**
