### PR TITLE
Kubernetes native development with quarkus and eclipse jkube

### PR DESCRIPTION
**Pull request by edeandrea**
Kubernetes native development with quarkus and eclipse jkube.

### CODE REVIEW

**Comment by edeandrea** [comment]
@maxandersen I'm not sure who I should tag here for a review?

**Comment by edeandrea** [comment]
@gsmet who should I ping for a review for this so that it can go live Thursday this week?

**Comment by edeandrea** [comment]
Is there someone here who can review/merge this in? @gastaldi maybe?

**Comment by gastaldi** [comment]
@edeandrea sure, I can do it, let me have a quick look and I'll merge it

**Comment by edeandrea** [comment]
Thank you very much @gastaldi !

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Done, thanks!

**Pull request merged**
