### PR TITLE
Create VS Code Quarkus 1.4.0 blog post

### PR DESCRIPTION
**Pull request by angelozerr**
Create VS Code Quarkus 1.4.0 blog post

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by fbricon** [comment]
Please wait for the actual release of vscode-quarkus 1.4.0 before merging this PR

**Comment by fbricon** [comment]
1.4.0 is [out](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-quarkus), this PR can now be merged (wink wink @maxandersen).

**Comment by fbricon** [comment]
How long does it take for the Quarkus blog to be updated?

**Comment by fbricon** [comment]
Yikes https://travis-ci.com/github/quarkusio/quarkusio.github.io/builds/160448241
> Error: could not read file /home/travis/build/quarkusio/quarkusio.github.io/_posts/2020-04-15-vscode-quarkus-1.4.0.adoc: invalid byte sequence in UTF-8

**Comment by gsmet** [comment]
I fixed it. I also added some basic author info for Angelo.

Please check the blog post in context before pushing a PR and before merging.

It would be even better if Angelo could add his gravatar hash here: https://github.com/quarkusio/quarkusio.github.io/commit/1be39f1f5a77c901b6013670b9fc01de9c7d3b56 .

Thanks.

**Comment by fbricon** [comment]
@gsmet thanks for the fix. I'll let @angelozerr take care of his gravatar hash, if he uses it.

**Pull request merged**
