### PR TITLE
Fix invalid feed.xml generation

### PR DESCRIPTION
**Pull request by djnalluri**
The inclusion of '&' in the title is generating an invalid feed.xml as it appears to not be correctly escaped.

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
FYI @maxandersen don't use & in titles.

**Comment by emmanuelbernard** [comment]
thanks @djnalluri , applied.

**Comment by maxandersen** [comment]
We are generating feeds without urlrncoding the generated content ? That's not good. I'll need to stop using # too then :)

**Comment by emmanuelbernard** [comment]
Not for the title. It's a common issue around static website generators

**Comment by maxandersen** [comment]
> Not for the title. It's a common issue around static website generators

[not true](https://github.com/quarkusio/quarkusio.github.io/pull/636) - it s a common issue for not proper made templates when original templates were fixed [7+ years ago](https://github.com/jekyll/jekyll/pull/1501) :)

**Pull request merged**
