### PR TITLE
Updated CSP

### PR DESCRIPTION
**Pull request by adelasofia**
Updates the Content Security Policy (CSP) to fix tracking issue in #237.

For more info regarding this change please see: https://docs.adobe.com/content/help/en/launch/using/reference/client-side-info/content-security-policy-csp.html

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
@adelasofia @jkbrock I tested Adela's changes which lower our note from A+ to B
https://observatory.mozilla.org/analyze/quarkus.io

what is the security team policy? Is B fine?

**Comment by gsmet** [comment]
@adelasofia @jkbrock can we have an answer to @emmanuelbernard 's question?

I bet we need to fix it.

**Comment by adelasofia** [comment]
@gsmet Under RH policy, security headers must receive a score of at least “B”, also this site doesn't host any Red Hat restricted data so the B score should be good.

I talked to Emmanuel about this back in the beginning of August but I should have left a comment on here too. This PR should be good to go.

**Comment by gsmet** [comment]
OK, merged then, thanks!

**Comment by emmanuelbernard** [comment]
Apologies I forgot to close that one when Adela updated me.

**Pull request merged**
