### PR TITLE
new blog entry covering Camel Quarkus

### PR DESCRIPTION
**Pull request by brunoNetId**
** If you are updating a guide, please submit your pull request to the main repository: https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc **

### CODE REVIEW

**Comment by brunoNetId** [comment]
When you find some time, could someone have a look at this new Camel Quarkus article?
It's the first time I contribute or submit a pull request so I'm not certain I did things 100% right, I hope I did.
thanks in advance

**Comment by edeandrea** [comment]
cc: @maxandersen

**Comment by gsmet** [comment]
I rebased to fix the conflicts and adjusted the dates for a publication on Tuesday. I'll wait for CI and check the result.

Unfortunately the content is too long for me to proofread everything with the current state of my eyes but what I read was very good so if there's no formatting issues, I'll merge.

**Comment by gsmet** [comment]
OK, content looks good, I just pushed a small adjustment to replace `mvn clean compile quarkus:dev` by `mvn clean quarkus:dev`. `compile` is done automatically.

**Comment by gsmet** [comment]
Will merge once CI is green. Content will be published on Tuesday. If you write me a tweet, I can tweet from the QuarkusIO account on Tuesday (or retweet a Camel one). Just let me know loudly :).

**Pull request merged**
