### PR TITLE
Adding a second GA tag to take advantage of GA4's capabilities

### PR DESCRIPTION
**Pull request by insectengine**
** If you are updating a guide, please submit your pull request to the main repository: https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc **

### CODE REVIEW

**Comment by maxandersen** [comment]
Why do we need the second one ? Shouldnt one be sufficient ?

Any of these slightly slows down the page so let's be careful.

**Comment by insectengine** [comment]
@maxandersen  -  The original GA number is owned by GoldenGate and it's controlled by RHD. We've gotten accidentally locked out in the past. We can't transfer that number to a new account and maintain the historical data (as per Axel). We are adding this new number to take advantage of GA's new reports in Google Analytics 4.  

https://support.google.com/analytics/answer/10089681?hl=en

**Comment by gastaldi** [comment]
Looks good: https://quarkusio-quarkusio-github-io-preview-pr-936.surge.sh/insights/

**Comment by maxandersen** [comment]
@insectengine seems two prs in one. its just the goan.js you want applied, right James?

**Comment by insectengine** [comment]
> @insectengine seems two prs in one. its just the goan.js you want applied, right James?

Correct... we cherry picked the change to the QI changes to another commit.

**Comment by maxandersen** [comment]
i've merged just the goan.js file and checked it with tagmanager extension that both tags are detected now.
 
where can I see the the new info ?

**Pull request closed without merging**
