### PR TITLE
447 with backend

### PR DESCRIPTION
**Pull request by Dufgui**
Here is the starter implementation with a separate backend: 
https://github.com/Dufgui/quarkus-generator

fix #447

### CODE REVIEW

**Comment by Dufgui** [comment]
Wait hosting of https://github.com/Dufgui/quarkus-generator and the url of the backend instead of localhost:8080

But the rest is ready for review, testable.

**Comment by Dufgui** [comment]
any news on this ?

**Comment by kenfinnigan** [comment]
Sorry @Dufgui, I haven't had a chance to look, and I know lots of others are traveling the last week or two.

Can you clarify whether the zip and file save JS files are actually needed if this expects the generator to be hosted somewhere? Or were they added in case we wanted the UI only option?

**Comment by Dufgui** [comment]
Sorry I forgot to remove them

**Comment by kenfinnigan** [comment]
No problem, just wanted to clarify

**Comment by Dufgui** [comment]
It's with a backend, so yes we must host the backend (https://github.com/Dufgui/quarkus-generator).
It's based on thorntail generator so I am quit sure that RedHat know how to host a thorntail. ;o)

**Comment by kenfinnigan** [comment]
Thorntail generator was hosted by one of our team on a custom system.

Not sure we have that option available still

**Comment by machi1990** [comment]
> It's based on thorntail ...

Why not quarkus? :-P

**Comment by Dufgui** [comment]
It can. You want it. Wait 1hour

Le mar. 21 mai 2019 à 21:30, Manyanda Chitimbo <notifications@github.com> a
écrit :

**Comment by Dufgui** [comment]
done ;o)

**Comment by gsmet** [comment]
Closing this one, we're going another route.

**Comment by Dufgui** [comment]
Is it possible to be included in the new route ? I am external of red hat so maybe it’s not possible. Please? @gsmet

**Comment by gsmet** [comment]
Hi @Dufgui,

So there is a launcher effort led by @ia3andy . It's nearly done AFAIK. The project is here: https://github.com/fabric8-launcher/launcher-quarkus .

Sorry for not getting to you earlier, I totally forgot about this PR until today when I reviewed the remaining site PR.

**Comment by Dufgui** [comment]
Sorry to read that. someone contact me to say I will be integrated in the
dev. So ok. I will work on my current PR

And take a look at it if I can contribute on the end.



Le jeu. 1 août 2019 à 16:40, Guillaume Smet <notifications@github.com> a
écrit :

**Pull request closed without merging**
