### PR TITLE
Update rabbitmq-reference.adoc

### PR DESCRIPTION
**Pull request by AndriiMaliuta**
Primitive changes: several typos and spaces :)

** If you are updating a guide, please submit your pull request to the main repository: https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc **

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Thanks.

**Comment by gsmet** [comment]
@AndriiMaliuta could you report your changes in the main repository here: https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/rabbitmq-reference.adoc ?

That's the source of truth for the guides.

**Comment by gsmet** [comment]
I created a PR here with you as the author of the commit: https://github.com/quarkusio/quarkus/pull/28069 .

**Comment by AndriiMaliuta** [comment]
@gsmet  , looks like https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/rabbitmq-reference.adoc does not contain those typos to be changed, so seems to be no nee for changes :)

**Comment by gsmet** [comment]
@AndriiMaliuta that's because I fixed them already by porting your patch there :). I release something tomorrow and wanted the fix in.

**Comment by AndriiMaliuta** [comment]
@gsmet  thanks a lot for applying the changes, hope this can help to improve the docs :)

**Pull request merged**
