### PR TITLE
Blog post - Quarkus monitoring with Cryostat

### PR DESCRIPTION
**Pull request by andrewazores**
@gsmet

### CODE REVIEW

**Comment by gsmet** [comment]
I approved the CI run, I'll take a look at the preview and if all is well, I'll schedule it for a publication tomorrow.

**Comment by gsmet** [comment]
@andrewazores if you can write me a tweet presenting the article, I will post it tomorrow from the QuarkusIO account.

**Comment by andrewazores** [comment]
"Check out this new blog post giving an overview of profiling and monitoring for Quarkus using Cryostat, including a configuration guide" ?

**Comment by gsmet** [comment]
@andrewazores https://twitter.com/QuarkusIO/status/1519300749573988352 \o/

**Pull request merged**
