### PR TITLE
Update march of IDEs features set of IntelliJ IDEA Ultimate

### PR DESCRIPTION
**Pull request by jreznot**
IntelliJ IDEA 2020.2 supports new project wizard and configuration files: .properties and YAML

https://www.jetbrains.com/idea/whatsnew/#frameworks--technologies

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
can I let you lead that @maxandersen BTW I don't think this blog entry has a ide tag.
Also, might be good to do a round of IDE invites on Insights :)

**Comment by emmanuelbernard** [comment]
thanks for the update @jreznot 
This is an old blog, so I was wondering how we can give the improvements more visibility to the community (on top of the fixes you gave)

**Comment by jreznot** [comment]
> thanks for the update @jreznot
> This is an old blog, so I was wondering how we can give the improvements more visibility to the community (on top of the fixes you gave)

Yes, that could be a new blog ) But for now I just want to set correct up-to-date marks in case users find the blog post.

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
