### PR TITLE
maven-tooling.adoc > small typo

### PR DESCRIPTION
**Pull request by devisions**
Just a small typo...

### CODE REVIEW

**Comment by gsmet** [comment]
This needs to be fixed in the main repo. I will push an update there.

Thanks for taking the time to report it!

**Comment by devisions** [comment]
@gsmet Guillaume, this means that next time - a similar case or some new material to contribute to the project - shall I do a PR to master?

**Comment by gsmet** [comment]
Sorry, I should have been clearer. The guides are hosted in the main repo here https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc and they are copied to the website when we release.

Thus the PR I created there: https://github.com/quarkusio/quarkus/pull/4475 .

**Comment by devisions** [comment]
No worries. Understood. Thanks for the details. 👍

**Pull request closed without merging**
