### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by mikrethor**
** If you are updating a guide, please submit your pull request to the main repository: https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc **

### CODE REVIEW

**Comment by gastaldi** [comment]
Can you open the PR against the `develop` branch instead?

**Comment by gastaldi** [comment]
Nevermind, it's already doing this.

**Comment by gastaldi** [comment]
I don't think it's a typo. The `'` means "architecture of Quarkus applications" not "Quarkus architecture".
Or am I missing something?

**Comment by mikrethor** [comment]
It would be ‘s and not only ‘. Tell me what to do and I will update the pr

**Comment by gsmet** [comment]
No, when finishing with an s, it's just `'`. That being said I would just remove the `'` as it really doesn't bring anything.

But... see what we automatically put in the description of your issue. This change needs to be done to the main repo.

**Comment by gastaldi** [comment]
Ah yes. It should be changed in https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/getting-started.adoc. 

Closing this one now. Thanks

**Pull request closed without merging**
