### PR TITLE
refactor TOC to be sticky

### PR DESCRIPTION
**Pull request by insectengine**
Addresses: https://github.com/quarkusio/quarkusio.github.io/issues/1352

1. Re arranged page to have TOC on the left
2. created two column layout (removed floating TOC) so scrolling content wouldn't clash with TOC. This also gives a more comfortable line length for reading than traditional full width content.
3. It's sticky so it stays on the top of the page when the page scrolls
4. There is a max height on the TOC with Scrolling. This allows the TOC to scroll when there is more links that the TOC view window (only happens on one guide I've found so far)

### CODE REVIEW

**Comment by metacosm** [comment]
A step in the right direction but why is there so much white space on the left side of the TOC? This seems like wasted space to me… that space exists even when the window is fairly narrow.

**Comment by insectengine** [comment]
Are you talking about this space?
thisspace

**Comment by insectengine** [comment]
@metacosm  The website isn't full width, it's centered with margins on either side that vary in width as the site is views on smaller screens. It starts at 13rem and has a medium size for tablets and small for mobile. We do this to prevent the site from exploding into gibberish on a huge screen. Switching from this to a full width for only the guide pages would be extremely jarring for the user.
border2
border

**Comment by insectengine** [comment]
@metacosm  - Changing the breakpoint for the spacing would be site wide. @ebullient  also suggested we fine tune some of the font sizes and whatnot at the mid range. We can do that but I think that should be a separate exercise and PR.

**Comment by insectengine** [comment]
Erin suggested moving the TOC to the right side of the page (where it originally was) so the important content is on the left (as read by left-right languages). I'm making this change and looking into adding javascript to track the users place in the TOC.

**Comment by metacosm** [comment]
Yes, the TOC on the left somehow bothered me but I couldn't decide if it was just because I wasn't used to it yet or something so I decided to let it slide 😉

**Comment by insectengine** [comment]
I'm going to not try and put a scroll spy indicator on the TOC as it's beyond my depth. If we have someone on the team skilled in JS that could make it work, that would be great.

**Review by ebullient — APPROVED** [review]

**Review by metacosm — APPROVED** [review]
Thanks!

**Comment by GabrielFoxDev** [comment]
Just opened an old tab to have it refreshed and greet me with that nice sticky ToC! :smile: 
Thanks!

**Pull request merged**
