### PR TITLE
Update and rename security.adoc to security-policy.adoc

### PR DESCRIPTION
**Pull request by rolfedh**
Fixes: https://github.com/quarkusio/quarkusio.github.io/issues/1664

### CODE REVIEW

**Comment by rolfedh** [comment]
@maxandersen @sberyozkin PTAL

**Comment by rolfedh** [comment]
@gsmet Please review and merge.
cc: @sberyozkin

**Comment by rolfedh** [comment]
@gsmet Updated and ready to merge.
cc: @sberyozkin

**Comment by sberyozkin** [comment]
Hi @gsmet Can you please look at this PR ?

**Review by gsmet — CHANGES_REQUESTED** [review]
I'm really not sure this change will change anything for Google searchability of the security guide... and it's breaking any external link to our security page which is a no-no.

We at the minimum need to put a redirect in place.

But even so, I'm not especially excited about it.

@maxandersen @insectengine WDYT?

**Comment by rolfedh** [comment]
> We at the minimum need to put a redirect in place.

Thanks. I've just added `_redirects/security.md` to address this.
I've also asked @sberyozkin to provide support for or a fuller explanation of the original issue in https://github.com/quarkusio/quarkusio.github.io/issues/1664

**Comment by maxandersen** [comment]
I've read but still I don't grok why changing this url is supposed to help? 

It is a good thing it's just quarkus.io/security. 

Why require the longer harder to remember/copy/read quarkus.io/security-policy url?

**Comment by maxandersen** [comment]
Changing the title I can buy or at least add security policy in top part of message but the url and redirect is a -1 from me.

**Comment by rolfedh** [comment]
> I've read but still I don't grok why changing this url is supposed to help?

An [SEO best practice](https://www.google.com/search?q=seo+file+names&oq=seo+file+name&gs_lcrp=EgZjaHJvbWUqCQgAEEUYOxiABDIJCAAQRRg7GIAEMgYIARBFGDkyCAgCEAAYFhgeMgoIAxAAGA8YFhgeMggIBBAAGBYYHjIICAUQABgWGB4yCAgGEAAYFhgeMgYIBxBFGEDSAQg2MDMwajBqN6gCALACAA&sourceid=chrome&ie=UTF-8) is to align the file name and the title of the document.

image

**Comment by maxandersen** [comment]
thats fine but lets please not use long winded "policy" names in URLs. URLs like these are to be remembered, typed and understood easily. 

quarkus.io/security is easy to remember, easy to type and most understand that page has stuff to do around quarkus security - let me read that .

quarkus.io/security-policy is not easy to remember, hard to type (is it with a or without a dash ? is it policy to not policy?, _ and if I see security-policy it is not a page I or many I can think of will go read :)z


and in addition quarkus.io/security is short and descriptive and use same keywords as in title and in page so I think we are covered.

**Comment by rolfedh** [comment]
Absolutely, I'm happy we've discussed this and come to a consensus. My aim was to put into action what I thought Sergey was suggesting. As it stands, we've only agreed on revising the title. So, I'll remove the changes for the redirect, altering the file name, and updating the links. The PR should be ready to merge shortly.

**Comment by rolfedh** [comment]
@gsmet ready to merge

**Comment by rolfedh** [comment]
Actually `quarkusio/quarkus/blob/master/SECURITY.md` states that
`The canonical version of this document is hosted on the Quarkus website at [Quarkus security](https://quarkus.io/security/).` In other words, the file in this PR is the only one that needs to be updated.

**Comment by rolfedh** [comment]
@gsmet The result of our conversations is a simple change to the title. I believe this is ready to merge now.

**Pull request closed without merging**
