### PR TITLE
Quarkus extension for VS Code blog post

### PR DESCRIPTION
**Pull request by xorye**
This is a blog post to showcase the features provided by the [Quarkus extension for VS Code](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-quarkus).

I've added a link to a Youtube video, I am getting this message: 
image
Is there any way to fix this?

I will be happy to make changes to the blog post content as needed.

Also, it would be great if we wait until Tuesday (Sept. 24) or Wednesday before publishing this blog post.

### CODE REVIEW

**Comment by maxandersen** [comment]
Haven't seen that kind of error before - very weird. I disabled all my extensions and it was still showing up as blocked.

**Comment by maxandersen** [comment]
whats weird is that the generated code are a `<iframe>` rather than a `<video>` tag from html5 which asciidoctor normally do.

**Comment by gsmet** [comment]
@emmanuelbernard I was wondering if it could be due to the CSP configuration you introduced on the website? Rings any bell?

**Comment by emmanuelbernard** [comment]
We have these settings

```
<META HTTP-EQUIV='Content-Security-Policy' CONTENT="default-src 'none'; script-src 'self' 'unsafe-eval' 'sha256-ANpuoVzuSex6VhqpYgsG25OHWVA1I+F6aGU04LoI+5s=' 'sha256-ipy9P/3rZZW06mTLAR0EnXvxSNcnfSDPLDuh3kzbB1w=' js.bizographics.com https://www.redhat.com assets.adobedtm.com jsonip.com https://ajax.googleapis.com https://www.googletagmanager.com https://www.google-analytics.com https://use.fontawesome.com; style-src 'self' https://fonts.googleapis.com https://use.fontawesome.com; img-src 'self' *; media-src 'self' ; frame-src https://www.googletagmanager.com; frame-ancestors 'none'; base-uri 'none'; object-src 'none'; form-action 'none'; font-src 'self' https://use.fontawesome.com https://fonts.gstatic.com;">
  <META HTTP-EQUIV='X-Frame-Options' CONTENT="DENY">
  <META HTTP-EQUIV='X-XSS-Protection' CONTENT="1; mode=block">
  <META HTTP-EQUIV='X-Content-Type-Options' CONTENT="nosniff">
 
```

**Comment by emmanuelbernard** [comment]
So @maxandersen you need to update the META HTTP-EQUIV Content-Security-Policy to have frame-src thedomainyouriframeisservedfrom.com

**Comment by maxandersen** [comment]
I fixed the HTTP-EQUIV and pushed to develop - @emmanuelbernard does that make it go live or is there a step more ?

**Comment by emmanuelbernard** [comment]
Makes it go live

**Comment by maxandersen** [comment]
yup saw that now :) first build failed, restarted in travis without a change and its now live!

thanks @xorye ! Great work on the extension and blog post!

**Comment by gsmet** [comment]
This post is awesome. Thanks for pushing it!

**Pull request merged**
