### PR TITLE
Super Hero Workshop

### PR DESCRIPTION
**Pull request by agoncal**
Adding the Super Hero workshop

** If you are updating a guide, please submit your pull request to the main repository: https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc **

### CODE REVIEW

**Comment by maxandersen** [comment]
I like the idea of pointing to workshops - but is there a more easily consumable format of it ? something less raw than a directory of asciidocs ?

**Comment by agoncal** [comment]
@maxandersen actually, @cescoffier publishing the HTML version of the workshop at : 

https://quarkus.io/quarkus-workshops/super-heros/

I just don't know if @cescoffier did it temporary and wants to leave it there (which would be great)

**Comment by cescoffier** [comment]
On 30 Oct 2019 at 11:18 +0100, Antonio Goncalves <notifications@github.com>, wrote:
> @maxandersen actually, @cescoffier publishing the HTML version of the workshop at :
> https://quarkus.io/quarkus-workshops/super-heros/
> I just don't know if @cescoffier did it temporary and wants to leave it there (which would be great)

No, it will still be there for a while.
Probably even updated once in a while.

**Comment by gsmet** [comment]
@maxandersen I let you merge these PRs.

**Comment by maxandersen** [comment]
thanks @agoncal I merged it using the quarkus.io based html page.

btw. what is the right company / entity should we use for you, is "Personal"  enough/correct ?

**Comment by maxandersen** [comment]
rebased and merged with date fixes.

**Comment by agoncal** [comment]
@maxandersen sorry, just saw your comment. "Personal" is enough ;o)

Thanks

**Pull request closed without merging**
