### PR TITLE
Remove adoc _templates, reuse sync script to maintain excludes

### PR DESCRIPTION
**Pull request by ebullient**
- Clean up `_templates`, which are not needed on the website.
- Reuse website sync script from the quarkus repo make it easier to maintain included/excluded resources.

Requires changes introduced in quarkusio/quarkus#27141.

### CODE REVIEW

**Comment by ebullient** [comment]
Should the GH Action be using `-DquicklyDocs`?

```
./mvnw -B -DskipTests -DskipITs -DskipExtensionValidation -Dskip.gradle.tests clean install
```

https://github.com/quarkusio/quarkusio.github.io/blob/735fd07d88816af577eaf36558bea5d9ae2e68a0/.github/workflows/sync-main-doc.yml#L39

**Comment by maxandersen** [comment]
> Should the GH Action be using `-DquicklyDocs`?

possibly - not actually sure when/what quicklyDocs is for ?

**Comment by maxandersen** [comment]
+1 on these changes. removes noise in output.

**Comment by ebullient** [comment]
> > Should the GH Action be using `-DquicklyDocs`?
> 
> possibly - not actually sure when/what quicklyDocs is for ?


https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/includes/compile-quarkus-quickly.adoc

**Review by gsmet — APPROVED** [review]

**Pull request merged**
