### PR TITLE
Added Twitter Card

### PR DESCRIPTION
**Pull request by myfear**
Added Twitter Card META info and sample graphic as discussed with @maxandersen .

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
I am not sure what twitter cards do, but I think @insectengine might want to redo it before or shortly after we push that PR.

**Comment by maxandersen** [comment]
twitter cards: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards

**Comment by maxandersen** [comment]
To test it, run `bundle jekyll serve` and run `ngrok http 4000` in another terminal go get a url you can test at https://cards-dev.twitter.com/validator 

to see the difference in behavior with similar pages using https://quarkus.io/*

**Comment by insectengine** [comment]
Gotcha... will work up one for the large image version:
https://issues.redhat.com/browse/DESIGN-1927

**Comment by insectengine** [comment]
Based on twitter... the large image size is 600x330. I've make some mockups of what that image could look like: 

https://design.jboss.org/quarkus/social/images/quarkus_twittercardimage_600x330_r1v1.jpg
https://design.jboss.org/quarkus/social/images/quarkus_twittercardimage_600x330_r1v2.jpg
https://design.jboss.org/quarkus/social/images/quarkus_twittercardimage_600x330_r1v3.jpg

**Comment by myfear** [comment]
I like v3. I think it would be great to have some quickly visible CTA included. "Learn more" or "quarkus.io" is awesome! This looks way better than my slapped together thing! Thank you 🤗

**Comment by gsmet** [comment]
I would go for either v1 or v3.

@emmanuelbernard ?

**Comment by emmanuelbernard** [comment]
No opinion except that the 1.0 mention is outdated.

**Comment by gsmet** [comment]
It's Quarkus.io in uppercase not 1.0 :).

**Comment by insectengine** [comment]
To address @myfear and @emmanuelbernard's concern... how about version 4: "Learn more at Quarkus.io"

https://design.jboss.org/quarkus/social/images/quarkus_twittercardimage_600x330_r1v4.jpg

**Comment by myfear** [comment]
Love it! 🤗

**Comment by gsmet** [comment]
@insectengine can you finalize this PR with your latest proposal? Looks like everyone is OK with it.

Thanks!

**Comment by emmanuelbernard** [comment]
I'm considering closing the PR as it seems we are not making progress. It happens, we are all busy. This message is a tombstone for me to close next time I see it and if there is no activity.

**Comment by insectengine** [comment]
@maxandersen : This seems to be the winner: https://design.jboss.org/quarkus/social/images/quarkus_twittercardimage_600x330_r1v4.jpg

Do you want to push on your side? Is this something @adelasofia can help with?

**Comment by adelasofia** [comment]
Closing this PR. I've pulled the changes and updated the image on #646

**Pull request closed without merging**
