### PR TITLE
Quarkus insights #84 to archive, Add #88.

### PR DESCRIPTION
**Pull request by insectengine**
** If you are updating a guide, please submit your pull request to the main repository: https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc **

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
There is a conflict.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
It says we can't merge because of conflicts.

**Comment by insectengine** [comment]
@gsmet  - Can we merge this?

**Comment by gsmet** [comment]
See my message above. I can’t merge, it says there are conflicts.

**Comment by gsmet** [comment]
Well, GitHub says otherwise. I will rebase myself.

**Comment by gsmet** [comment]
So yes there was a conflict. To rebase, you need to do `git pull upstream develop --rebase` and it will tell you if there are conflicts.

Anyway, it's fixed, I will merge once CI is green.

**Pull request merged**
