### PR TITLE
Add Kafka, Avro and Schema Registry guide

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
** If you are updating a guide, please submit your pull request to the main repository: https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc **

### CODE REVIEW

**Comment by cescoffier** [comment]
Related to https://github.com/quarkusio/quarkus/pull/16503.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Do not merge before the next release - as it's a new guide.

**Comment by michalszynkiewicz** [comment]
@gsmet added to guides-main.yaml too now

**Comment by cescoffier** [comment]
@gsmet can you check? It should be ok.

**Review by gsmet — APPROVED** [review]
I adjusted the PR to only change `main`. I will change `latest` when we release 2.0.

**Pull request merged**
