### PR TITLE
Converted FAQ, Security to AsciiDoc

### PR DESCRIPTION
**Pull request by adelasofia**
** If you are updating a guide, please submit your pull request to the main repository: https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc **

Fixes: https://issues.redhat.com/browse/DESIGN-1957

This PR converts the /faq and /security source to AsciiDoc.

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
Hey Adela, this does not seem to fix DESIGN-1957 when I try. I don't see a section sign § when I hover on a section title

**Comment by emmanuelbernard** [comment]
And the anchor url is not selectable

**Comment by adelasofia** [comment]
@emmanuelbernard Hmm odd, which browser/version are you using?

**Comment by emmanuelbernard** [comment]
Firefox 77 on macOS

**Comment by emmanuelbernard** [comment]
Facepalm. I was checking the live website and not localhost. Sorry.

**Comment by adelasofia** [comment]
Lol! No worries 😃

**Pull request merged**
