### PR TITLE
Virtual threads - blog post 6

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by maxandersen** [comment]
...i'm reading this and wondering what is specific in this to virtual threads? this is how you containerize (almost) any java/quarkus app or am I missing something?

**Comment by cescoffier** [comment]
No, you are not missing anything. We made it plain boring. I might have to highlight that.

**Comment by maxandersen** [comment]
> No, you are not missing anything. We made it plain boring. I might have to highlight that.

yeah - if that is the intention I would definitely highlifht it. 

Possibly even consider not making that separate post and just point to info how to deploy in docs and focus on the different aspect going forward?

**Comment by cescoffier** [comment]
I got asked for that specific post. So I believe there is a need.

**Comment by cescoffier** [comment]
Maybe I should copy that post to the docs (as ... it's not crystal clear (too many possibilities))

**Pull request merged**
